version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ghostcode
      POSTGRES_PASSWORD: 171201@Monkey
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ghostcode@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 171201@Monkey
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  sonarqube:
    image: sonarqube:latest
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/var/lib/sonarqube
      - sonarqube-logs:/opt/sonarqube/logs
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
      SONARQUBE_JDBC_URL: jdbc:postgresql://192.168.33.10:5432/ghostcode/sonar
      SONARQUBE_JDBC_USERNAME: ghostcode
      SONARQUBE_JDBC_PASSWORD: 171201@Monkey

volumes:
  postgres-data:
  pgadmin-data:
  sonarqube-data:
  sonarqube-logs: